RCM/config/routes.rb
Rails.application.routes.draw do
 

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  root 'static_pages#index'
  get 'static_pages/home'
  get 'static_pages/simple_character'
  get 'static_pages/profile'
  get 'static_pages/show_all_users'
  get 'static_pages/show_all_campaigns'
  get '/static_pages/change_role/:id' => 'static_pages#change_role' ,:as => :change_role
  get '/static_pages/block_user/:id' => 'static_pages#block_user' ,:as => :block_user
  get '/static_pages/unblock_user/:id' => 'static_pages#unblock_user' ,:as => :unblock_user

  get 'users/:user_id/campaigns/:id/manage_characters' => 'campaigns#manage_characters', :as => :manage_characters
  post 'users/:user_id/campaigns/:id/add_character' => 'campaigns#add_character', :as => :add_character
  post 'users/:user_id/campaigns/:id/remove_character/:c' => 'campaigns#remove_character', :as => :remove_character
  post 'users/:user_id/campaigns/:id' => 'campaigns#inviter', :as => :inviter#
  post 'users/:user_id/invites/:id' => 'invites#accept', :as => :accept#
  #get '/static_pages/help' =>'campaigns#accept', :as => :accept#
  get '/callback', to: 'events#callback', as: 'callback'
  post 'users/:user_id/characters/:id' => 'characters#export', :as  => :export
  post 'users/:user_id/requests/:id' => 'requests#accept', :as => :acceptI
  post 'users/:user_id/planners/:id' => 'planners#accept', :as => :acceptP

	
  resources :events
	
  resources :users do
    resources :characters
    resources :campaigns
    resources :messages
    resources :invites
    resources :requests
    resources :planners

  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RCM/app/models/character.rb
class Character < ApplicationRecord
	validates :name, presence: true
	validates :lvl, presence: true, inclusion: 1..20
	validates :class_type, presence: true
	validates :race, presence: true
	validates :info, presence: true
	
	belongs_to :user, optional: true
end

RCM/app/controllers/characters_controller.rb
class CharactersController < ApplicationController
	before_action :authenticate_user!
	before_action :check
	
	def index
		@user = User.find(params[:user_id])
		@characters = @user.characters
	end

	def show
		@user = User.find(params[:user_id])
		@character = Character.find(params[:id])
	end
	
	def new
		@user = User.find(params[:user_id])
		@character = Character.new
	end

	def edit
		@user = User.find(params[:user_id])
		@character = Character.find(params[:id])
	end

	def create
		@user = User.find(params[:user_id])
		@character = @user.characters.new(character_params)

    if @character.save
      redirect_to user_character_path(@user, @character)
    else
    	render :new
    end
    
	end

	def update
		@user = User.find(params[:user_id])
  	@character = Character.find(params[:id])
 
  	if @character.update(character_params)
    	redirect_to user_character_path(@user, @character)
  	else
    	render 'edit'
  	end
	end

	def destroy
		@user = User.find(params[:user_id])
		@character = @user.characters.find(params[:id])
		@character.destroy

		redirect_to user_characters_path(@user)
	end
	
	def export
		@user = User.find(params[:user_id])
		@character = @user.characters.find(params[:id])
		@toEx = ""+@character.name.to_s + "," + @character.class.to_s + "," + @character.race.to_s+ ","+@character.info.to_s
		Clipboard.copy(@toEx)
	end

	private def character_params
    params.require(:character).permit(:name, :lvl, :race, :class_type, :info)
  end

  private def check
  	@user = User.find(params[:user_id])
  	if ((@user != current_user) && !current_user.admin?)
			redirect_to static_pages_home_url
		end
  end
end

RCM/app/helpers/characters_helper.rb
module CharactersHelper
end

RCM/app/views/characters/edit.html.erb
<h1 class="text-center page-title">Edit Your Character</h1>

<div class=" card shadow-lg col-lg-4 col-md-6 bg-white mx-auto pt-2" >
    <%= form_with(model: [@user, @character], local: true) do |form| %>
  
      <p>
        <strong>Name:</strong>
        <%= @character.name %>
      </p>

      <p>
        <strong><%= form.label :lvl %></strong>
        <%= number_field(:character, :lvl, in: 1..20, step: 1) %>
      </p>

      <p>
        <strong>Race:</strong>
        <%= @character.race %>
      </p>

      <p>
        <strong>Class:</strong>
        <%= @character.class_type %>
      </p>

      <p>
        <strong><%= form.label :info %></strong><br>
        <%= form.text_area :info %>
      </p>
      
      <div class="actions text-center">
        <p>
          <%= form.submit %>
        </p>
      </div>
 
      <% if @character.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@character.errors.count, "error") %> prohibited
            this character from being saved:
          </h2>
          <ul>
          <% @character.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    <% end %>
  </div>

RCM/app/views/characters/index.html.erb
<% provide(:title, "My Characters") %>
<!DOCTYPE html>
<html>
  
  <body>
    <h1 class="text-center page-title">These Are Your Characters</h1>
    <hr>
      
    <div class="text-center">
      <%= link_to 'Create New Character', new_user_character_path, class: "btn  btn-outline-primary waves-effect" %>
    </div>
    <hr>
  
      <% @characters.each_slice(2) do |slice| %>
        <div class="row">
            <% slice.each do |character| %>
              <div class="card shadow-lg col-lg-4 col-md-4 col-sm-3 bg-white mx-auto pt-3 pb-3">

                <p><strong>Name: </strong> <%= character.name %> </p>
                <p><strong>Level: </strong> <%= character.lvl %></p>
                <p><strong>Race: </strong> <%= character.race %></p>
                <p><strong>Class: </strong> <%= character.class_type %></p>
                <p><strong>Info: </strong><%= character.info %></p>
                
                <div class="text-center">
                  <p><%= link_to 'Show', user_character_path(current_user, character), class: "btn  btn-outline-primary-bis waves-effect" %>
                  <%= link_to 'Edit', edit_user_character_path(current_user, character), class: "btn  btn-outline-primary-bis waves-effect" %>
                  <%= link_to 'Delete', user_character_path(current_user, character), data: { confirm: 'Are you sure?' } , :method => :delete,  class: "btn  btn-outline-primary-bis waves-effect" %></p>
                </div>

              </div>
            <% end %>
          </div>
        <% end %>
    
  </body>
</html>

RCM/app/views/characters/new.html.erb
<% provide(:title, "Create a Character") %>
<!DOCTYPE html>
  

  <div class=" card shadow-lg col-lg-4 col-md-6 bg-white mx-auto pt-2" >
    <h2 class="text-center mt-3">Create a New Character</h2>

    <%= form_with scope: :character, url: user_characters_path do |form| %>

      <div class="field">
        <p>
          <%= form.label :name %>
          <%= form.text_field :name %>
        </p>
      </div>
      
      <div class="field">
        <p>
          <%= form.label :lvl%>
          <%= number_field(:character, :lvl, in: 1..20, step: 1) %>
        </p>
      </div>
    
      <div class="field">
        <p>
          <%= label_tag(:race, "Race") %>
          <%= form.select :race, ['race1', 'race2'], include_blank: true %>
        </p>
      </div>

      <div class="field">
        <p>
          <%= label_tag(:class_type, "Class") %>
          <%= form.select :class_type, ['class1', 'class2'], include_blank: true %>
        </p>
      </div>

      <div class="field">
        <p>
          <%= form.label :info %><br>
          <%= form.text_area :info %>
        </p>
      </div>
 
      <div class="actions text-center">
        <p>
          <%= form.submit %>
        </p>
      </div>

          <!--ERRORS-->
      <% if @character.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <div id="error_explanation">
            <h2>
              <%= pluralize(@character.errors.count, "error") %>
            </h2>
            <ul>
              <% @character.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>

    <% end %>

RCM/app/views/characters/show.html.erb
<% provide(:title, "Character") %>

<!DOCTYPE html>
  <h1 class="text-center page-title">Here's Your Character</h1>

  <div class="row">
    <div class="card shadow-lg col-lg-4 col-md-4 col-sm-3 bg-white mx-auto pt-3 pb-3">
		  <p>
  		  <strong>Name:</strong>
  		  <%= @character.name %>
		  </p>

		  <p>
  		  <strong>Level:</strong>
  		  <%= @character.lvl %>
		  </p>
 
		  <p>
  		  <strong>Race:</strong>
  		  <%= @character.race %>
		  </p>

		  <p>
  		  <strong>Class:</strong>
  		  <%= @character.class_type %>
		  </p>

		  <p>
  		  <strong>Info:</strong>
  		  <%= @character.info %>
		  </p>

      <div class="text-center">

        <p>
          <%= link_to 'Edit', edit_user_character_path(@user), class: "btn  btn-outline-primary-bis waves-effect" %> 
        </p>

        <p>
          <%= button_to 'Delete', user_character_path(@user),
              method: :delete,
              data: { confirm: 'Are you sure?' }, class: "btn  btn-outline-primary-bis waves-effect" %>
        </p>
        
		    <p>
          <%= link_to 'Back to My Characters', user_characters_path, class: "btn  btn-outline-primary-bis waves-effect" %>
        </p>

        <p>
          <%= link_to 'Export', export_path, method: :post, class: "btn  btn-outline-primary-bis waves-effect" %> 
        </p>

      </div>
    </div>
  </div>