RCM/config/routes.rb
Rails.application.routes.draw do
 

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  root 'static_pages#index'
  get 'static_pages/home'
  get 'static_pages/simple_character'
  get 'static_pages/profile'
  get 'static_pages/show_all_users'
  get 'static_pages/show_all_campaigns'
  get '/static_pages/change_role/:id' => 'static_pages#change_role' ,:as => :change_role
  get '/static_pages/block_user/:id' => 'static_pages#block_user' ,:as => :block_user
  get '/static_pages/unblock_user/:id' => 'static_pages#unblock_user' ,:as => :unblock_user

  get 'users/:user_id/campaigns/:id/manage_characters' => 'campaigns#manage_characters', :as => :manage_characters
  post 'users/:user_id/campaigns/:id/add_character' => 'campaigns#add_character', :as => :add_character
  post 'users/:user_id/campaigns/:id/remove_character/:c' => 'campaigns#remove_character', :as => :remove_character
  post 'users/:user_id/campaigns/:id' => 'campaigns#inviter', :as => :inviter#
  post 'users/:user_id/invites/:id' => 'invites#accept', :as => :accept#
  #get '/static_pages/help' =>'campaigns#accept', :as => :accept#
  get '/callback', to: 'events#callback', as: 'callback'
  post 'users/:user_id/characters/:id' => 'characters#export', :as  => :export
  post 'users/:user_id/requests/:id' => 'requests#accept', :as => :acceptI
  post 'users/:user_id/planners/:id' => 'planners#accept', :as => :acceptP

	
  resources :events
	
  resources :users do
    resources :characters
    resources :campaigns
    resources :messages
    resources :invites
    resources :requests
    resources :planners

  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RCM/app/models/campaign.rb
class Campaign < ApplicationRecord
	belongs_to :user, optional: true
	has_many :characters, dependent: :destroy
	validates :title, presence: true
	validates :description, presence: true
	@@lastC = ""
	def self.setLast (lastCa)
		@@lastC = lastCa
	end
	def self.getLast
		@@lastC
	end
	@@lastId
	def self.setLastId (li)
		@@lastId = li
	end
	def self.getLastId
		@@lastId
	end
	@@destId
	def self.setDestId (di)
		@@destId = di
	end
	def self.getDestId
		@@destId
	end
	@@userer
	def self.setUserer (us)
		@@userer = us
	end
	def getUserer
		@@userer
	end
end

RCM/app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
	before_action :authenticate_user!
	before_action :check, except: [:show]
	
	def index
		@user = User.find(params[:user_id])
		@campaigns = @user.campaigns
	end

	def show
		@user = User.find(params[:user_id])
		@campaign = Campaign.find(params[:id])
		@characters = @campaign.characters
	end
	
	def new
		@user = User.find(params[:user_id])
		@campaign = Campaign.new
	end

	def edit
		@user = User.find(params[:user_id])
		@campaign = Campaign.find(params[:id])
	end

	def create
		@user = User.find(params[:user_id])
		@campaign = current_user.campaigns.new(campaign_params)
		@campaign.master = current_user.username

		if @campaign.save
			redirect_to user_campaign_path(@user, @campaign)
		else
			render :new
		end
	end

	def update
		@user = User.find(params[:user_id])
  	@campaign = Campaign.find(params[:id])
 
  	if @campaign.update(campaign_params)
    	redirect_to user_campaign_path(@user, @campaign)
  	else
    	render 'edit'
  	end
	end

	def destroy
		@user = User.find(params[:user_id])
		@campaign = @user.campaigns.find(params[:id])
		@campaign.destroy

		redirect_to user_campaigns_path(@user)
	end

	def manage_characters
		@user = User.find(params[:user_id])
		@campaign = @user.campaigns.find(params[:id])
		@characters = @campaign.characters
	end

	def remove_character
		@user = User.find(params[:user_id])
		@campaign = @user.campaigns.find(params[:id])
		@characters = @campaign.characters
		@characters.delete(params[:c])

		redirect_to manage_characters_path
	end

	#This is just a proof of concept. It works but it needs changes. Also it needs a check to
	#see to whom the character belogns to
	def add_character
		@campaign = Campaign.find(params[:id])
		@character_to_add = Character.find_by_name(params[:character][:character_id])
		@owner_of_c=User.find(@character_to_add.user_id)
		@campaign.characters << @character_to_add
		redirect_to manage_characters_path
	end
	def accept_invite
		@user = Campaign.getUserer
		
	end
	def inviter
		@user=User.find(params[:user_id])
		@campaign = @user.campaigns.find(params[:id])
		Campaign.setLast(@campaign.title)
		Campaign.setLastId(@campaign.id)
		redirect_to new_user_invite_path
	end
	#helper_method :invite
	
	def accept
		#@owner = User.find(params[:user_id])
		
		@invite = Invite.find(params[:id])
		@owner = @User.find(@invite.destid)
		@sender = User.find(@invite.senderid)
		@campaign = Campaign.find(@invite.campaignid)
		@character_to_add = @owner.characters.find(1)
		@campaign.characters << @character_to_add
		destroy
	end
	#helper_method :accept


	private def campaign_params
    params.require(:campaign).permit(:title, :description)
  end

  private def check
  	@user = User.find(params[:user_id])
  	if ((@user != current_user) && !current_user.admin?)
			redirect_to static_pages_home_url
		end
  end

end

RCM/app/helpers/campaigns_helper.rb
module CampaignsHelper
end

RCM/app/views/campaigns/edit.html.erb
<h1 class="text-center page-title">Edit Your Campaign</h1>
<div class=" card shadow-lg col-lg-4 col-md-6 bg-white mx-auto pt-2" >
  <%= form_with(model: [@user, @campaign], local: true) do |form| %>
  
    <p>
      <strong>Name:</strong>
      <%= @campaign.title %>
    </p>

    <p>
      <strong> <%= form.label :description %></strong><br>
      <%= form.text_area :description %>
    </p>
    
    <div class="actions text-center">
      <p>
        <%= form.submit %>
      </p>
    </div>

    <% if @campaign.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@campaign.errors.count, "error") %> prohibited
          this campaign from being saved:
        </h2>
        <ul>
          <% @campaign.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
 
  <% end %>

RCM/app/views/campaigns/index.html.erb
<% provide(:title, "My Campaigns") %>
<!DOCTYPE html>
<html>
  
  <body>
    <h1 class="text-center page-title">All Your Campaigns</h1>
    <hr>
  
    <div class="text-center">
      <%= link_to 'Create New Campaign', new_user_campaign_path, class: "btn  btn-outline-primary waves-effect" %>
    </div>
    <hr>

      <% @campaigns.each_slice(2) do |slice| %>
        <div class="row">
          <% slice.each do |campaign| %>
            <div class="card shadow-lg col-lg-4 col-md-4 col-sm-3 bg-white mx-auto pt-3 pb-3">
              <p><strong>Title: </strong> <%= campaign.title %></p>
              <p><strong>Description: </strong><%= campaign.description %></p>
              <div class="text-center">
                
                <p><%= link_to 'Show', user_campaign_path(current_user, campaign), class: "btn  btn-outline-primary-bis waves-effect" %>
                  <%= link_to 'Edit', edit_user_campaign_path(current_user, campaign), class: "btn  btn-outline-primary-bis waves-effect" %></p>

                <p>
                  <%= link_to 'Invite', user_campaign_path(current_user,campaign), method: :post, class: "btn  btn-outline-primary-bis waves-effect" %>
                  <%= link_to 'Delete', user_campaign_path(current_user, campaign), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn  btn-outline-primary-bis waves-effect" %>
                </p>
              </div>
            </div>
        <% end %>
      </div>
    <% end %>

RCM/app/views/campaigns/manage_characters.html.erb
<% provide(:title, "Manage Characters") %>
<!DOCTYPE html>
<html>
  
  <body>
    <h1 class="text-center page-title ">Manage this campaign's characters</h1>
    <hr>
      
      <table class="table table-bordered">
        <thead>
          <caption>Campaign's Characters</caption>
          <tr>
            <th>Character's Owner</th>
            <th>Character's name</th>
            <th>Remove</th>
          </tr>
        </thead>

        <tbody>
          <% @characters.each do |c| %>
            <tr>
        	     <td><%= c.user_id  %></td> <!-- Probably need to add column to characters with username of the owner -->
        	     <td><%= c.name %></td>
        	     <td><%= button_to 'Remove', remove_character_path(current_user, @campaign, c) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </body>
</html>

RCM/app/views/campaigns/new.html.erb
<% provide(:title, "Create a Campaign") %>
<!DOCTYPE html>

  <div class=" card shadow-lg col-lg-4 col-md-6 bg-white mx-auto pt-2" >
    <h2 class="text-center mt-3 pb-3">Create a New Campaign</h2>
      <%= form_with scope: :campaign, url: user_campaigns_path do |form| %>

        <div class="field">
          <p>
            <%= form.label :title %>
            <%= form.text_field :title %>
          </p>
        </div>

        <div class="field">
          <p>
            <%= form.label :description %><br>
            <%= form.text_area :description %>
          </p>
        </div>

        <div class="actions text-center">
          <p>
            <%= form.submit %>
          </p>
        </div>
      <% end %>

      <!--ERRORS-->
      <% if @campaign.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <div id="error_explanation">
            <h2>
              <%= pluralize(@campaign.errors.count, "error") %>
            </h2>
            <ul>
              <% @campaign.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    </div>

RCM/app/views/campaigns/show.html.erb
<% provide(:title, "Campaign") %>

<!DOCTYPE html>
  <h1 class="text-center page-title">Here's Your Campaign</h1>
    
    <div class="row">
      <div class="card shadow-lg col-lg-4 col-md-4 col-sm-3 bg-white mx-auto pt-3 pb-3">

        <%= form_with url: add_character_path do |form| %>
          <p>
            <strong>Master:</strong>
            <%= @campaign.master %>
          </p>

		      <p>
  		      <strong>Title:</strong>
  		      <%= @campaign.title %>
		      </p>

		      <p>
  		      <strong>Description:</strong>
  		      <%= @campaign.description %>
		      </p>

          <% if (current_user.username == @campaign.master) %>
            <p>
              <table class="table bordered-table">
                <thead>
                  <tr>
                    <th>Character's Owner</th>
                    <th>Character's name</th>
                  </tr>
                </thead>
                <tbody>
                  <% @characters.each do |c| %>
                    <tr>
                      <td><%= User.find(c.user_id).username  %></td>
                      <td><%= c.name %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </p>
          <% end %>


        <div class="text-center">
          <p>
            
            <% if current_user.admin? %>
              <div class="field">
                <p>
                  <%= form.label :character%> 
                  <%= collection_select( :character, :character_id, Character.all, :name, :name, {}, {:multiple => false}) %>
                </p>
              </div>

              <%= form.submit "Add This Character", class: "btn  btn-outline-primary-bis waves-effect" %>
              <!--<%= link_to 'Add Character', add_character_path, class: "btn  btn-outline-primary-bis waves-effect" %>  This was mostly for testing -->
            <% end %>

            <% if (current_user.username == @campaign.master || current_user.admin?) %>
              <%= link_to 'Manage Characters', manage_characters_path, class: "btn  btn-outline-primary-bis waves-effect" %>
            <% end %>

          </p>
        </div>
        <% end %>

        <div class="text-center">
		      <p>
            
            <%= button_to 'New session event', new_event_path, method: :get, class: "btn  btn-outline-primary-bis waves-effect" %>
            <p></p>

            <%= link_to 'Edit', edit_user_campaign_path(@user), class: "btn  btn-outline-primary-bis waves-effect" %>

            <%= link_to 'Delete', user_campaign_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn  btn-outline-primary-bis waves-effect" %>

            <hr>

            <%= link_to 'Back to My Campaigns', user_campaigns_path, class: "btn  btn-outline-primary-bis waves-effect" %>
    
          </p>
        </div>
      </div>
    </div>