RCM/config/routes.rb
Rails.application.routes.draw do
 

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  root 'static_pages#index'
  get 'static_pages/home'
  get 'static_pages/simple_character'
  get 'static_pages/profile'
  get 'static_pages/show_all_users'
  get 'static_pages/show_all_campaigns'
  get '/static_pages/change_role/:id' => 'static_pages#change_role' ,:as => :change_role
  get '/static_pages/block_user/:id' => 'static_pages#block_user' ,:as => :block_user
  get '/static_pages/unblock_user/:id' => 'static_pages#unblock_user' ,:as => :unblock_user

  get 'users/:user_id/campaigns/:id/manage_characters' => 'campaigns#manage_characters', :as => :manage_characters
  post 'users/:user_id/campaigns/:id/add_character' => 'campaigns#add_character', :as => :add_character
  post 'users/:user_id/campaigns/:id/remove_character/:c' => 'campaigns#remove_character', :as => :remove_character
  post 'users/:user_id/campaigns/:id' => 'campaigns#inviter', :as => :inviter#
  post 'users/:user_id/invites/:id' => 'invites#accept', :as => :accept#
  #get '/static_pages/help' =>'campaigns#accept', :as => :accept#
  get '/callback', to: 'events#callback', as: 'callback'
  post 'users/:user_id/characters/:id' => 'characters#export', :as  => :export
  post 'users/:user_id/requests/:id' => 'requests#accept', :as => :acceptI
  post 'users/:user_id/planners/:id' => 'planners#accept', :as => :acceptP

	
  resources :events
	
  resources :users do
    resources :characters
    resources :campaigns
    resources :messages
    resources :invites
    resources :requests
    resources :planners

  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RCM/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action 	:authenticate_user!, :except => [:simple_character, :index]
	before_action :check
	def index
	end
  	
  	
  	def home
  	end

  	def simple_character
  	end
	 
  	def profile
  	end

  	def show_all_users
  		@users= User.all
  	end

    def show_all_campaigns
      @users = User.all
    end

  	def change_role
  		@user=User.find(params[:id])
  		@user.update_attribute(:admin, !@user.admin?)
  		redirect_to static_pages_show_all_users_url
  	end
  	def block_user
  		@user=User.find(params[:id])
  		@user.update_attribute(:block, true)
  		redirect_to static_pages_show_all_users_url
  	end
  	def unblock_user
  		@user=User.find(params[:id])
  		@user.update_attribute(:block, false)
  		redirect_to static_pages_show_all_users_url
  	end

private 

	def check
		if (params[:action] == "index") && user_signed_in?
			
			redirect_to static_pages_home_url
		end
		if (params[:action] == "show_all_users" || params[:action] == "change_role" ||params[:action] == "block_user" || params[:action] == "unblock_user" ) && !current_user.admin?
			redirect_to static_pages_home_url
		end
    if (params[:action] == "show_all_campaigns") && !current_user.admin?
      redirect_to static_pages_home_url
    end
		if user_signed_in? && !current_user.admin? && (current_user.email =="pivarim@gmail.com" || current_user.email =="perottofederico@gmail.com" ||current_user.email =="deluca.1753532@studenti.uniroma1.it")
				current_user.update_attribute :admin, true
			end
	end

end

RCM/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

RCM/app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
  
  <body>
    <h1 class="text-center page-title">Hi <%= current_user.username%>! This is your homepage.</h1>
    
    <div class="row text-center home">
      <div class="col-3">
        <div class="card" style="width: 16rem; height: 14rem;">
          <div class="card-body">
            <h5 class="card-title">Characters</h5>
            <p class="card-text text-muted">Here you can view and edit all of your characters, or create new ones!</p><br>
            <%= link_to 'My Characters', user_characters_path(current_user.id), class: "btn  btn-outline-primary-bis waves-effect" %> 
          </div>
        </div>
      </div>

      <div class= "col-3">
        <div class="card" style="width: 16rem; height: 14rem;">
          <div class="card-body">
            <h5 class="card-title">Campaigns</h5>
            <p class="card-text text-muted">Here you can view and edit all of your campaigns or create new ones, or you send invites to other users!</p>
            <%= link_to 'My Campaigns', user_campaigns_path(current_user.id), class: "btn  btn-outline-primary-bis waves-effect" %>
          </div>
        </div> 
      </div>
        
      <div class= "col-3">
        <div class="card" style="width: 16rem; height: 14rem;">
          <div class="card-body">
            <h5 class="card-title">Invites</h5>
            <p class="card-text text-muted">Here you can view and manage and answer the invites you have received to join a camaign.</p>
            <%= link_to 'Invites', user_invites_path(current_user.id), class: "btn  btn-outline-primary-bis waves-effect" %>
          </div>
        </div>
      </div>

      <div class="col-3">
        <div class="card" style="width: 16rem; height: 14rem;">
          <div class="card-body">
            <h5 class="card-title">Requests</h5>
            <p class="card-text text-muted">Here you can see and manage all the requests you have received to join a campaign.</p>
            <%= link_to 'Requests', user_requests_path(current_user.id), class: "btn  btn-outline-primary-bis waves-effect" %> 
          </div>
        </div>
      </div>
    </div>

    <div class="row text-center home">

      <div class="col-3">
        <div class="card" style="width: 16rem; height: 14rem;">
          <div class="card-body">
            <h5 class="card-title">Profile</h5>
            <p class="card-text text-muted pb-4">Here you can view and modify your info, or delete your account.</p>
            <%= link_to "View Profile", static_pages_profile_path, class: "btn  btn-outline-primary-bis waves-effect"%>
          </div>
        </div>
      </div>

      <div class="col-3">
        <% if current_user.admin? %>
        <div class="card" style="width: 16rem; height: 14rem;">
          <div class="card-body">
            <h5 class="card-title">All Users</h5>
            <p class="card-text text-muted pb-5 ">As an admin, you can view a list of all the registered users.</p>
            <%= link_to "All Users", static_pages_show_all_users_path ,class: "btn  btn-outline-primary-bis waves-effect" %>
          </div>
        </div>
        <% end %>
      </div>

      <div class="col-3">
        <% if current_user.admin? %>
        <div class="card" style="width: 16rem; height: 14rem;">
          <div class="card-body">
            <h5 class="card-title">All Campaigns</h5>
            <p class="card-text text-muted pb-4">As an admin, you can view a list of all the existing campaigns</p>
            <%= link_to "All Campaigns", static_pages_show_all_campaigns_path, class: "btn  btn-outline-primary-bis waves-effect" %>
          </div>
        </div>
        <% end %>
      </div>

      <div class="col-3">
        <div class="card" style="width: 16rem; height: 14rem;">
          <div class="card-body">
            <h5 class="card-title">Planners</h5>
            <p class="card-text text-muted">Here you can see all the game session you have sent to or received from your friends</p>
            <%= link_to 'Session Planning', user_planners_path(current_user.id), class: "btn  btn-outline-primary-bis waves-effect" %> 
          </div>
        </div>
      </div>
    </div>
      
    </div>

  </body>
</html>

RCM/app/views/static_pages/index.html.erb
<% provide(:title, "Index") %>
<!DOCTYPE html>
<html>
  
  <body>
  	
    <div class="row">
        <div class="col-lg-8 col-md-6">
          <h1 class="title text-white m-5">
            RPG Campaign Manager
          </h1>
          <p class="subtitle text-white ml-5">RPG Campaign Manager is an easy and quick tool to create and manage your campaigns and your characters. You can join a campaign with one of your characters or create one of your own, and you can also plan your game sessions. Try it out!
          </p>

          <%= link_to "View a sample character!", static_pages_simple_character_path, class:"btn btn-light m-5"%>
        <!-- <button type="button" class="btn btn-light m-5">View a sample character!</button> -->
        </div>
    
        <!-- <div class="col-lg-4 col-md-6 bg-white main-form pt-5">
          <h2 class="text-center mt-5">Login</h2>
          
          <form class="mt-5 p-3">
            <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
  
            <div class="form-group">
              <label for="exampleInputPassword1">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
  
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1">
              <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
        
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div> -->
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= yield %>
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
  </body>
</html>

RCM/app/views/static_pages/profile.html.erb
<% provide(:title, "Profile") %>
<!DOCTYPE html>
<html>
  
  <body>
    <h1 class="text-center page-title">This is your profile.</h1>
    
    <div class="card shadow-lg col-lg-4 col-md-3 col-sm-3 bg-white mx-auto pt-3 pb-3">
      <div> <b>E-Mail:</b>  <%= current_user.email%> </div>

      <div> <b>Nickname:</b> <%= current_user.username%> </div>

      <% if  current_user.admin %>
		     <div> <b> You're an Admin!</b> </div>
      <% end %>
    </div>

    <div class="row pt-3">
      <div class="col text-center">
    <p><%= link_to "Edit Your Profile", edit_user_registration_path, class: "btn  btn-outline-primary waves-effect" %></p>

    <p><%= link_to "Home Page", static_pages_home_url, class: "btn  btn-outline-primary waves-effect" %><br /></p>
      </div>
    </div>
  </body>
</html>

RCM/app/views/static_pages/show_all_campaigns.erb
<% provide(:title, "All Campaigns") %>
<!DOCTYPE html>
<h1 class="text-center page-title">Listing All Campaigns</h1>
<hr>
 
  <% @users.each do |user| %>
    <div class="text-center page-title-bis"><strong> Username: </strong><%= user.username %></div><br>
    <% user.campaigns.each_slice(2) do |slice| %>
      <div class="row">
        <% slice.each do |campaign| %>
          <div class="card shadow-lg col-lg-4 col-md-4 col-sm-3 bg-white mx-auto pt-3 pb-3 text-center"> 
            <p><strong> Title: </strong><%= campaign.title %></p><br>
            <p><strong> Description: </strong><%= campaign.description %></p><br>
            <p><%= link_to "View this campaign", user_campaign_path(user.id, campaign.id), class: "btn  btn-outline-primary-bis waves-effect" %></p>
            <br>
          </div>
        <% end %>
      </div>
    <% end %>
    <hr>
  <% end %>

RCM/app/views/static_pages/show_all_users.html.erb
<% provide(:title, "All Users") %>
<!DOCTYPE html>
<h1 class="text-center page-title">Listing All Users</h1>
<hr>
 

  <% @users.each_slice(3) do |slice| %>
    <div class="row">
      <% slice.each do |user| %>
        <div class="card shadow-lg col-lg-4 col-md-4 col-sm-3 bg-white mx-auto pt-3 pb-3"> 
          <strong> Email: </strong><%= user.email %><br />
          <strong> Username: </strong><%= user.username %><br />
          <strong> Role: </strong> <% if user.admin %>
            Admin
          <% else %>
            User
          <% end %> <br>
          <% if user.block %>
            This user is blocked
          <% end %>

            <div class="text-center">
              <p> <%= link_to "View his characters", user_characters_path(user.id), class: "btn  btn-outline-primary-bis waves-effect" %> </p>

              <% if  !user.admin %>
                <% if  !user.block %>
                  <p><%= link_to "Block User", block_user_path(user.id), class: "btn  btn-outline-primary-bis waves-effect mx-auto" %><br /></p>
                <% else%>
                  <p><%= link_to "Unblock User", unblock_user_path(user.id), class: "btn  btn-outline-primary-bis waves-effect" %><br /></p>
                <% end %>
                <p><%= link_to "Upgrade to Admin", change_role_path(user.id), class: "btn  btn-outline-primary-bis waves-effect" %><br /></p>
              <% elsif (current_user.email =="pivarim@gmail.com" || current_user.email =="perottofederico@gmail.com" ||current_user.email =="deluca.1753532@studenti.uniroma1.it" )||(user.email==current_user.email)%>
                <p><%= link_to "Downgrade to User", change_role_path(user.id), class: "btn  btn-outline-primary-bis waves-effect", id: user.id %><br /></p>
              <% end %>
            </div>
        </div>
      <% end %>
    </div>
  <% end %>

RCM/app/views/static_pages/simple_character.html.erb
<% provide(:title, "Simple Characters") %>
<!DOCTYPE html>
<html>
  
  <body>
    <h1 class="text-center page-title">These are examples of the characters you can create with RPG Campaign Manager</h1>
    
    <div class="row">
      <div class="card shadow-lg col-lg-4 col-md-4 col-sm-3 bg-white mx-auto pt-3 pb-3">
        <p><strong>Name: </strong> Chronos <br /></p>
        <p><strong>Level: </strong> 6 <br /></p>
        <p><strong>Race: </strong> Elf <br /></p>
        <p><strong>Class: </strong> Barbarian <br /></p>
        <p><strong>Info: </strong> Born in the palace of an elven house, Chronos lives a comfortable youth. He is the son of the clan leader, and is used to having everything he wants: the most beautiful clothes, the most expensive weapons, and the best preceptors. From his teachers he learned the rudiments of magic, letters, poetry, history, while his weapon master teached him the basic steps of the "singing of the blade", the most difficult elf fencing technique. Confident and proud of his lineage, Chronos planned to leave his home to travel the world; at the rejection of his parents he decides to escape secretly after having stolen from the palace's armory the best and his father's sword. After a few days they came across a band of thieves, who defeat him in minutes and steal everything. Chronos, betrayed by his own bravado, learns the lesson of humility.</p>
        </tr>
      </div>

      <div class="card shadow-lg col-lg-4 col-md-4 col-sm-3 bg-white mx-auto pt-3 pb-3">
        <p><strong>Name: </strong> Rodos <br /></p>
        <p><strong>Level: </strong> 1 <br /></p>
        <p><strong>Race: </strong> Human <br /></p>
        <p><strong>Class: </strong> Bard <br /></p>
        <p><strong>Info: </strong> The life of Rodos has been marked by some memory problems. As a boy he had the habit of taking other people's things, slipping where he didn't have to, hiding to surprise his relatives from behind, who every time ended up risking heart attack. After years of these increasingly elaborate and amusing "pranksters jokes" (for Rodos of course), his brothers decided to lead him a little. During the beating Rodos fell on his head against a boulder from there he began to forget things from one moment to the next. One day trying to go home, convinced that he is following the right path, he goes even further. Not finding his village he takes a new path, and although he does not know the places he visits, he is convinced that he is on the right path, and that he knows perfectly every place he meets. For several months he has been traveling from city to city convinced that he is on his way home.</p>
      </div>

      <div class="card shadow-lg col-lg-4 col-md-4 col-sm-3 bg-white mx-auto pt-3 pb-3">
        <p><strong>Name: </strong> Zeus <br /></p>
        <p><strong>Level: </strong> 15 <br /></p>
        <p><strong>Race: </strong> Dwarf <br /></p>
        <p><strong>Class: </strong> Mage <br /></p>
        <p><strong>Info: </strong>  Zeus is the young son of a blacksmith, and has learned from his father the art of forging and handling weapons. With the outbreak of war he decided to put himself at the service of an order of knights as a mercenary soldier, both because he was fascinated by the exploits of the paladins, and in the hope of traveling the world and finding magical or particular weapons like the ones his father keeps. During his stay at the castle of the knights he meets Dargor, a priest of the goddess Airmed, who becomes his spiritual guide and his teacher of life. Since then the two travel together.</p>
      </div>
    </div>

    <div class="text-center pt-4"><%= link_to "Back to index page", root_url, class: "btn  btn-outline-primary waves-effect"%><br /></div>

  </body>
</html>