RCM/config/routes.rb
Rails.application.routes.draw do
 

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  root 'static_pages#index'
  get 'static_pages/home'
  get 'static_pages/simple_character'
  get 'static_pages/profile'
  get 'static_pages/show_all_users'
  get 'static_pages/show_all_campaigns'
  get '/static_pages/change_role/:id' => 'static_pages#change_role' ,:as => :change_role
  get '/static_pages/block_user/:id' => 'static_pages#block_user' ,:as => :block_user
  get '/static_pages/unblock_user/:id' => 'static_pages#unblock_user' ,:as => :unblock_user

  get 'users/:user_id/campaigns/:id/manage_characters' => 'campaigns#manage_characters', :as => :manage_characters
  post 'users/:user_id/campaigns/:id/add_character' => 'campaigns#add_character', :as => :add_character
  post 'users/:user_id/campaigns/:id/remove_character/:c' => 'campaigns#remove_character', :as => :remove_character
  post 'users/:user_id/campaigns/:id' => 'campaigns#inviter', :as => :inviter#
  post 'users/:user_id/invites/:id' => 'invites#accept', :as => :accept#
  #get '/static_pages/help' =>'campaigns#accept', :as => :accept#
  get '/callback', to: 'events#callback', as: 'callback'
  post 'users/:user_id/characters/:id' => 'characters#export', :as  => :export
  post 'users/:user_id/requests/:id' => 'requests#accept', :as => :acceptI
  post 'users/:user_id/planners/:id' => 'planners#accept', :as => :acceptP

	
  resources :events
	
  resources :users do
    resources :characters
    resources :campaigns
    resources :messages
    resources :invites
    resources :requests
    resources :planners

  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RCM/app/models/planner.rb
class Planner < ApplicationRecord
  belongs_to :user
end

RCM/app/controllers/planners_controller.rb
class PlannersController < ApplicationController
	def index
		@user = User.find(params[:user_id])
		@planners = Planner.where(:dest => @user.username)
		#modify later
		@myP = @user.planners
	end
	def show
		@user = User.find(params[:user_id])
		@planner = Planner.find(params[:id])
		@planner.destid=@user.id
	end
	
	def new
		@user = User.find(params[:user_id])
		@planner = Planner.new
	end

	def edit
		@user = User.find(params[:user_id])
		@planner = Planner.find(params[:id])
	end

	def create
		@user = User.find(params[:user_id])
		@planner = @user.planners.new(planner_params)
		@planner.sender = @user.username
		@planner.senderid = @user.id
		
		if @planner.save
			redirect_to user_planners_path(@user)
		else
			render :new
		end
    
	end	
	def update
		@user = User.find(params[:user_id])
		@planner = Planner.find(params[:id])
 
		if @planner.update(invite_params)
			redirect_to user_planners_path(@user, @planner)
		else
    	render 'edit'
		end
	end

	def destroy
		@user = User.find(params[:user_id])
		@planner = Planner.find(params[:id])
#call destroy from show mybe solves problem
		@planner.destroy

		redirect_to user_planners_path(@user)
	end
	
	def accept
		@planner = Planner.find(params[:id])
		@planner.answer = "yes"
		@planner.save
	end
	helper_method :accept

	private def planner_params
		params.require(:planner).permit(:dest, :day, :month, :year)
	end

	private def check
		@user = User.find(params[:user_id])
		if ((@user != current_user) && !current_user.admin?)
			redirect_to static_pages_home_url
		end
	end
end

RCM/app/helpers/planners_helper.rb
module PlannersHelper
end

RCM/app/views/planners/edit.html.erb
<h1>Edit Your Character</h1>
 
<%= form_with(model: [@user, @character], local: true) do |form| %>
 
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@character.errors.count, "error") %> prohibited
        this character from being saved:
      </h2>
      <ul>
        <% @character.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <strong>Name:</strong>
    <%= @character.name %>
  </p>

  <p>
    <%= form.label :lvl %><br>
    <%= number_field(:character, :lvl, in: 1..20, step: 1) %>
  </p>

  <p>
    <strong>Race:</strong>
    <%= @character.race %>
  </p>

  <p>
    <strong>Class:</strong>
    <%= @character.class_type %>
  </p>

  <p>
    <%= form.label :info %><br>
    <%= form.text_area :info %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', user_characters_path %>

RCM/app/views/planners/index.html.erb
<% provide(:title, "Session planning") %>
<!DOCTYPE html>
<html>
  
  <body>
    <h1 class="text-center page-title">Session planning</h1>
    <hr>

      <div class=" text-center">
        <%= link_to 'Plan A New Session', new_user_planner_path(@user, @planner), class: "btn  btn-outline-primary waves-effect" %>
      </div>
    <hr>
    
      <table class="table table-bordered">
        <caption>Session Plans Received</caption>
        <thead>
          <tr>
            <th scope="col">Session Plan From</th>
            <th scope="col">Answer</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>

        <tbody>
          <% @planners.each do |planner| %>
        
            <tr class="text text-center">
              <td><%= planner.sender %> <!--Answer: <%= planner.answer %></td> -->         
              <td> 
                <% if(planner.answer=="yes") %>
                  Accepted
                <% else %>
                  <%= link_to 'Answer', user_planner_path(current_user, planner),  class: "btn  btn-outline-primary waves-effect" %>    
                <% end %>
              </td>
              <td><%= link_to 'Delete', user_planner_path(current_user, planner),
                data: { confirm: 'Are you sure?' } , :method => :delete,  class: "btn  btn-outline-primary waves-effect" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>


      <table class="table table-bordered">
        <thead>
          <caption>Session Plans Sent</caption>
          <tr>
            <th scope="col">Session Plan to</th>
            <th scope="col">Date</th>
            <th scope="col">Answer</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>

        <tbody>
          <% @myP.each do |planner| %>
            <tr class="text text-center">
              <td><%= planner.dest %> </td>
              <td> <%= planner.day %>/<%= planner.month %>/<%= planner.year %> </td>
              <td> <%= planner.answer %> </td>
              <td><%= link_to 'Delete', user_planner_path(current_user, planner),
                data: { confirm: 'Are you sure?' } , :method => :delete,  class: "btn  btn-outline-primary waves-effect" %></td>
            </tr>
          <% end %>
        </tbody>
      
      </table>
    
  </body>
</html>

RCM/app/views/planners/new.html.erb
<% provide(:title, "Session planning") %>
<!DOCTYPE html>
<html>
  <body>

    <div class=" card shadow-lg col-lg-4 col-md-6 bg-white mx-auto pt-2" >
      <h2 class="text-center mt-3 pb-3">Create a New Session</h2>
      <%= form_with scope: :planner, url: user_planners_path do |form| %>
        
        <div class="field">
          <p>
            <strong><%= form.label :dest %></strong>
            <%= form.text_field :dest %>
          </p>
        </div>
        
        <div class="field">
          <p>
            <strong><%= form.label :day%></strong>
            <%= number_field(:planner, :day, in: 1..31, step: 1) %>
          </p>
        </div>
          
        <div class="field">
          <p>
            <strong><%= form.label :month%> </strong>
            <%= number_field(:planner, :month, in: 1..12, step: 1) %>
          </p>
        </div>        

        <div class="field">
          <p>
            <strong><%= form.label :year%></strong>
            <%= number_field(:planner, :year, in: 2019..2030, step: 1) %>
          </p>
        </div>
        
        <div class="text-center">
          <p>
            <%= form.submit %>
          </p>
        </div>
      <% end %>
          <!--ERRORS-->
      <% if @planner.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <div id="error_explanation">
            <h2>
              <%= pluralize(@planner.errors.count, "error") %>
            </h2>
            <ul>
              <% @planner.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>

      <hr>

      <div class="text-center">
        <p><%= link_to 'Back', user_planners_path, class: "btn  btn-outline-primary-bis waves-effect" %></p>
      </div>
    </div>

  </body>
</html>

RCM/app/views/planners/show.html.erb
<% provide(:title, "session planning") %>

<!DOCTYPE html>
<html>

<body>

    <div class=" card shadow-lg col-lg-4 col-md-6 bg-white mx-auto pt-2" >
      <h2 class="text-center mt-3 pb-3">Accept the Invite?  </h2>
      <div class="field">
		    <p>
  		    <strong>Day:</strong>
  		    <%= @planner.day %>
		    </p>
      </div>

      <div class="field">
		    <p>
		      <strong>Month:</strong>
  		    <%= @planner.month %>
		    </p>
      </div>

      <div class="field">
		    <p>
		      <strong>Year:</strong>
  		    <%= @planner.year %>
		    </p>
      </div>

        <div class="text-center">
    		  <p>
		        <%= link_to 'Accept', acceptP_path ,method: :post, class: "btn  btn-outline-primary-bis waves-effect"%>
            <%= link_to 'Decline', user_planner_path(@user),
              method: :delete,
              data: { confirm: 'Are you sure?' }, class: "btn  btn-outline-primary-bis waves-effect" %>
          </p>
        </div>

        <hr>

        <div class="text-center">
          <p>
            <%= link_to 'Back To Your Sessions', user_planners_path, class: "btn  btn-outline-primary-bis waves-effect" %>
          </p>
        </div>
  	
    <br>
	</body>
</html>